In [1]:
3+4

7

In [5]:
### Heading

* this is first point

In [4]:
import os

In [6]:
os.getcwd()

'C:\\Users\\jaink\\OneDrive\\Desktop\\ML training\\day 7'

os.chdir('C:\\Users\\jaink\\OneDrive\\Desktop\\ML training\\day 6')

In [9]:
os.listdir('C:\\Users\\jaink\\OneDrive\\Desktop\\ML training')

['.ipynb_checkpoints',
 '.py',
 'Day 1.py',
 'Day 1.txt',
 'day 6.py',
 'day 7',
 'day5.py',
 'Untitled.ipynb']

In [10]:
os.mkdir('Empty_folder')

In [12]:
#to remove a folder
os.rmdir('Empty_folder')

FileNotFoundError: [WinError 2] The system cannot find the file specified: 'Empty_folder'

## Random

In [14]:
import random

In [15]:
val=random.random()
print(val)

0.8470192477962206


In [16]:
val2=random.randint(1,10)

In [19]:
print(val2)

2


In [21]:
m=['hi','hello','hayy','howdy']
val=random.choice(m,k=3)
print(val)

TypeError: choice() got an unexpected keyword argument 'k'

In [22]:
m=['hi','hello','hayy','howdy']
val=random.choices(m,k=3)
print(val)

['hayy', 'howdy', 'hello']


In [23]:
#shuffle
random.shuffle(m)
print(m)

['hi', 'howdy', 'hello', 'hayy']


In [1]:
n=np.array([[1,2,3,3] ,[2,3,4,5] ,[54,56,3,5] ]

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [7]:
n=np.array([[1,2,3,3] ,[2,3,4,5] ,[54,56,3,5]])

In [8]:
n.shape

(3, 4)

In [9]:
n=np.array([[1,2,3,4], [11,22,33,40] ,[5,7,9,90]])

In [10]:
n[1,3]

40

In [11]:
N

NameError: name 'N' is not defined

In [12]:
n

array([[ 1,  2,  3,  4],
       [11, 22, 33, 40],
       [ 5,  7,  9, 90]])

In [13]:
n[1,3]

40

In [14]:
n[0,3]

4

In [15]:
n[1,2]


33

In [16]:
n[1,2],[1,3]

(33, [1, 3])

In [18]:
n[0][1:3]

array([2, 3])

In [19]:
n[1,0:3]

array([11, 22, 33])

In [20]:
n[1:2,2:4]

array([[33, 40]])

In [ ]:
#SYNTAX=n[row,column]

In [21]:
n[1:,2:]

array([[33, 40],
       [ 9, 90]])

In [22]:
n[1:3,2:4]

array([[33, 40],
       [ 9, 90]])

In [23]:
n[1:1,2:3]

array([], shape=(0, 1), dtype=int32)

In [24]:
n[1:2]

array([[11, 22, 33, 40]])

# arrange

In [26]:
list(range(5,51))

[5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50]

In [27]:
np.arrange(5,51)

AttributeError: module 'numpy' has no attribute 'arrange'

In [28]:
np.arange(5,51)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [29]:
np.arnage(5.5,50.3)

AttributeError: module 'numpy' has no attribute 'arnage'

In [31]:
np.arange(5.5,50.3,2)

array([ 5.5,  7.5,  9.5, 11.5, 13.5, 15.5, 17.5, 19.5, 21.5, 23.5, 25.5,
       27.5, 29.5, 31.5, 33.5, 35.5, 37.5, 39.5, 41.5, 43.5, 45.5, 47.5,
       49.5])

# reshape

In [32]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
a=np.arange(20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [36]:
a.max()


NameError: name 'a' is not defined

In [34]:
np.sqrt(144)

12.0

In [35]:
np.max()

TypeError: _amax_dispatcher() missing 1 required positional argument: 'a'

In [37]:
a

NameError: name 'a' is not defined

In [38]:
a=np.arange(20).reshape(5,4)

In [39]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [40]:
a.mean()

9.5

In [41]:
a.argmax() #highest value index

19

In [42]:
a.argmin()  #lowest value index

0

In [43]:
a*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30],
       [32, 34, 36, 38]])

In [44]:
a+10

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25],
       [26, 27, 28, 29]])

# Random

In [45]:
np.random.rand(5,5)

array([[0.51688064, 0.68990898, 0.27209046, 0.90624484, 0.79885582],
       [0.78297999, 0.29879206, 0.82962151, 0.87198704, 0.46625993],
       [0.89600378, 0.66696073, 0.1417867 , 0.11515829, 0.14432298],
       [0.04105206, 0.15450432, 0.45502962, 0.53486677, 0.8156877 ],
       [0.57341404, 0.80532992, 0.92730768, 0.12568597, 0.53673302]])

In [46]:
np.random.randint(2,3)

2

In [47]:
np.random.rand(2)

array([0.7875171 , 0.11561649])

In [48]:
np.random.randn(2,2)

array([[ 0.88523604, -0.07696339],
       [-0.91010792, -0.48188024]])

In [50]:
np.random.randint(9,90,12) #12- no of values

array([53, 58, 88, 40, 85, 65, 59, 31, 46, 77, 22, 41])

In [52]:
np.random.randint(9,90,12).reshape(3,4)

array([[71, 44, 60, 13],
       [71, 17, 62, 12],
       [32, 11, 28, 47]])

In [53]:
a=np.random.randint(9,90,12)

In [54]:
a

array([42, 34, 35, 66, 14, 86, 30, 32, 44, 69, 60, 12])

In [55]:
a.sum

<function ndarray.sum>

In [56]:
a=np.random.randint(9,90,12).reshape(3,4)

In [57]:
a.sum()

620

In [58]:
a.sum(axis=1) #row wise add

array([234, 175, 211])

In [59]:
a.sum(axis =0) #column wise add

array([133, 154, 189, 144])

# 3D

In [60]:
n=np.array([[[4,40] ,[5,50] ,[6,60] ] ,[[3,30] ,[4,40] ,[6,60] ] ,[ [8,80] ,[9,90] ,[4,40] ] ])

In [61]:
n

array([[[ 4, 40],
        [ 5, 50],
        [ 6, 60]],

       [[ 3, 30],
        [ 4, 40],
        [ 6, 60]],

       [[ 8, 80],
        [ 9, 90],
        [ 4, 40]]])

In [62]:
n.shape

(3, 3, 2)

In [63]:
n.arange(48).reshape(4,3,4)

AttributeError: 'numpy.ndarray' object has no attribute 'arange'

In [64]:
# Nan- not a number

In [65]:
x=np.array([12,57,np.nan,66,20,np.nan])

In [66]:
x

array([12., 57., nan, 66., 20., nan])

In [67]:
x.dtype

dtype('float64')