In [1]:
import numpy as np

In [2]:
a=np.array([])
b=np.array([1,2,3,45,0])
c=np.array([[12,3,4],[4,5,8]])

In [3]:
a

array([], dtype=float64)

In [4]:
b

array([ 1,  2,  3, 45,  0])

In [5]:
c

array([[12,  3,  4],
       [ 4,  5,  8]])

In [6]:
type(a)

numpy.ndarray

In [7]:
b

array([ 1,  2,  3, 45,  0])

In [8]:
type(b)

numpy.ndarray

In [12]:
b.ndim

1

In [9]:
c

array([[12,  3,  4],
       [ 4,  5,  8]])

In [16]:
c.shape

(2, 3)

In [13]:
c.ndim

2

In [10]:
type(c)

numpy.ndarray

In [11]:
a.ndim

1

In [14]:
c.size

6

In [15]:
b.size

5

In [17]:
n=np.array([ [1,2,3,4,] , [20,10,40,30],[200,49,67,89] ])

In [18]:
n.shape

(3, 4)